### ISSUE TITLE
Invalid FIX Message Header

### ISSUE THREAD

**Issue by tom-smalls** [LMAX-Exchange/nanofix#4]
When using the FixMessageBuilder object, if you're building a fix message whose message type is not predefined in the MsgType object then you have to use the append() method the builder provides. If the first call to the builder is not appending the MsgType, then the fix message produced is invalid (MsgType will not be the 3rd fix tag.

Valid Message: `8=FIX.4.2|9=64|35=4|123=Y|36=10|56=tom|49=JUDD|52=20160808-12:02:50.967|34=100|10=237|`

```
new FixMessageBuilder()
                .append(35, "4")
                .msgSeqNum(100)
                .append(123, "Y")
                .append(36, "10")
                .send();
```

Invalid Message: `8=FIX.4.2|9=64|34=100|123=Y|35=4|36=10|56=tom|49=JUDD|52=20160808-12:02:50.967|10=237|`

```
new FixMessageBuilder()
                .msgSeqNum(100)
                .append(123, "Y")
                .append(35, "4")
                .append(36, "10")
                .send();
```

The Standard Message Header for FIX defines that MsgType should be the third field in a message (http://btobits.com/fixopaedia/fixdic44/index.html)

**Comment by juddgaddie** [comment]
This is expected behaviour the FixMessageBuilder doesn't enforce order of fields. Fields are written in the order that they are appended to the builder. JavaDoc and test added.

**Comment by tom-smalls** [comment]
I have to say I disagree Fix version, body length, message type, and checksum are the only fields in fix messages that have to be in a certain position. Fix version, body length, and checksum all have their positions determined internally to the FixMessageBuilder (not by when they are appended), whilst message type is not, which provides an inconsistency with the api. Fields where order matters should all be treated the same.
